dashboard/src/components/customization/CustomizableFooter.vue, dashboard/src/components/customization/CustomizableHeader.vue, dashboard/src/components/settings/SystemSettings.vue, dashboard/src/main.js, e2e-tests/cypress/integration/settings_spec.js, service/src/main/java/skills/controller/PublicConfigController.groovy, service/src/main/java/skills/services/SystemSettingsService.groovy, service/src/main/java/skills/services/settings/Settings.java, service/src/main/java/skills/settings/SystemSettings.groovy, service/src/test/java/skills/intTests/PublicConfigSpecs.groovy, service/src/test/java/skills/intTests/SettingsSpecs.groovy, service/src/test/java/skills/intTests/utils/SkillsService.groovy
One thing to consider is whether we want to allow html element ids in the custom header/footer. It seems like someone could unintentionally(or intentionally) by specifying an id already in use elsewhere in the dom. At the moment they are permitted.
=> Ticket#32/dashboard configuration for header footer

call-stack-profiler/pom.xml, service/pom.xml
Version upgrades to remove security vulnerabilities
=> Security Updates

service/src/main/java/skills/services/events/SkillEventsService.groovy, service/src/main/java/skills/utils/MetricsLogger.groovy, service/src/main/java/skills/utils/ToolMetricsLogger.groovy, service/src/test/java/skills/services/SkillEventServiceUnitSpecs.groovy
=> T#297/tool metrics

dashboard/babel.config.js, dashboard/package.json, dashboard/src/App.vue, dashboard/src/components/access/ResetPassword.vue, dashboard/src/components/badges/global/GlobalBadges.vue, dashboard/src/components/header/Breadcrumb.vue, dashboard/src/components/header/DashboardFooter.vue, dashboard/src/components/levels/global/LevelSelector.vue, dashboard/src/components/levels/global/ProjectSelector.vue, dashboard/src/components/metrics/skill/SkillEventsOverTime.vue, dashboard/src/components/projects/MyProject.vue, dashboard/src/components/projects/MyProjects.vue, dashboard/src/components/skills/ChildRowSkillsDisplay.vue, dashboard/src/components/skills/dependencies/DependantsGraph.vue, dashboard/src/components/subjects/EditSubject.vue, dashboard/src/components/subjects/Subject.vue, dashboard/src/components/utils/ExistingUserInput.vue, dashboard/src/components/utils/iconPicker/IconPicker.vue, dashboard/src/components/utils/table/SkillsBTable.vue, dashboard/src/interceptors/clientVersionInterceptor.js, dashboard/tests/e2e/custom-assertions/elementCount.js, dashboard/tests/e2e/nightwatch.conf.js, dashboard/tests/e2e/runner.js, dashboard/tests/unit/components/metrics/skills/SkillsUsageHelper.spec.js
Hay! Hope you are having a good, day night or whatever. I removed some unneeded comments that weren't used and added semicolons to missing places. Also added a small syntax sugar, thanks for reviewing, loves <3
=> enhancement: use optional chaining, add semicolons and remove unneeded comments

.gitignore, scripts/getDashboardVersion.js, service/src/main/java/skills/services/VersionService.groovy
Per #1546 - fix an issue with the file not being read from the classpath in the JAR, rename file, throw exception when file is missing
=> #1546 Fix an issue with the file not being found in the jar

service/src/main/java/skills/services/VersionService.groovy
Per #1560, make some changes to the Version service to cause the app to fail to start up if there's no version file and change some logging.
=> #1560 Make adjustments to the version service to improve functionality

service/src/main/java/skills/skillLoading/SkillsLoader.groovy, service/src/main/java/skills/storage/model/DisplayOrderRes.groovy, service/src/main/java/skills/storage/repos/SkillDefRepo.groovy, service/src/test/java/skills/intTests/clientDisplay/SingleSkillSummarySpec.groovy, service/src/test/java/skills/intTests/utils/SkillsService.groovy
Should resolve the issues with groups not being accounted for correctly
=> T#1523/next prev skill buttons

dashboard/src/components/settings/ProjectSettings.vue, e2e-tests/cypress/e2e/settings-toggle_specs.js
Per #1608, this is to fix settings labels not properly updating, which was being caused by the boolean value being either a string or an actual boolean
=> T#1608/fix label updates

client-display/src/userSkills/skill/progress/SkillProgress2.vue, client-display/src/userSkills/skill/progress/SkillsProgressList.vue, dashboard/src/components/settings/ProjectSettings.vue, e2e-tests/cypress/e2e/client-display/client-display-skill_groups_spec.js, service/src/main/java/skills/controller/PublicConfigController.groovy, service/src/main/java/skills/services/settings/Settings.java, service/src/main/java/skills/skillLoading/SkillsLoader.groovy, service/src/main/java/skills/skillLoading/model/SkillsSummaryGroup.groovy, service/src/main/java/skills/storage/repos/SkillDefWithExtraRepo.groovy, service/src/test/java/skills/intTests/clientDisplay/ClientDisplaySubjSummarySpec.groovy
Adds the ability to toggle Group Descriptions as being Always On from the project Settings page as an administrator, per #1499
=> T#1499/show group descriptions

client-display/src/userSkills/skill/progress/SkillsProgressList.vue, client-display/src/userSkills/subject/SubjectDetails.vue, e2e-tests/cypress/e2e/client-display/client-display-last-seen_spec.js, e2e-tests/cypress/e2e/client-display/client-display-skill-paging_spec.js
Fixes some issues with skills in groups and adds more tests to ensure both the last viewed feature is included and excluded appropriately (i.e. on global badges) and that the paging feature is excluded from cross project dependent skill pages.
=> T#1524/last viewed indicator

client-display/src/userSkills/skill/progress/SkillsProgressList.vue, client-display/src/userSkills/subject/SubjectDetails.vue, e2e-tests/cypress/e2e/client-display/client-display-last-seen_spec.js
Fix an issue with groups overwriting the last seen property even if there was not a last seen item in the group
=> #1524 Fix an issue with groups overwriting the last seen

dashboard/src/components/utils/TableStateUtil.js, e2e-tests/cypress/e2e/tableSortPersist_spec.js
Fixes the issue found by @mosefer where table state was being overwritten
=> T#524/table state overwrite

dashboard/src/components/badges/BadgeSkills.vue, dashboard/src/components/badges/global/GlobalBadgeSkills.vue, dashboard/src/components/skills/SimpleSkillsTable.vue, e2e-tests/cypress/e2e/badges_spec.js, e2e-tests/cypress/e2e/global_badges_spec.js, service/src/main/java/skills/storage/repos/SkillRelDefRepo.groovy
Resolves the issue with the Manage button not appearing appropriately.  On the Global Badges table, it will no longer appear at all (a setting was added to hide the button completely), while on the Badges table, it will always appear (the necessary subject Id wasn't being returned).
=> T#1748/manage button bug

service/src/test/java/skills/intTests/metrics/skill/NoUsagePostAchievementUsersBuilderSpec.groovy, service/src/test/java/skills/intTests/metrics/skill/UsagePostAchievementUsersBuilderSpec.groovy
Changes the sorting in two of the tests which should resolve the test failure
=> #1668 Modify sorting in tests

dashboard/src/components/users/UserSkillsPerformed.vue
Changes the property used to show a table is loading
=> #1910 Change table loading property

service/src/main/java/skills/storage/repos/UserEventsRepo.groovy, service/src/test/java/skills/intTests/metrics/skill/UsagePostAchievementUsersBuilderSpec.groovy
Fixes the issue with counts in the tables not matching up with counts in the graphs
=> #1915 Change the method of calculating the counts

service/src/main/java/skills/skillLoading/SkillsLoader.groovy, service/src/main/java/skills/storage/repos/SkillDefRepo.groovy, service/src/test/java/skills/intTests/clientDisplay/SingleSkillSummarySpec.groovy
Should fix the issue of gaps in display orders causing the relevant Prev / Next button to not appear
=> #1925 Refactor how previous and next buttons are created

e2e-tests/cypress/e2e/projects_modal_management_spec.js, e2e-tests/cypress/e2e/save_state_spec.js, e2e-tests/cypress/e2e/subjects_spec.js
Makes some changes to tests to hopefully resolve the CI issues
=> T#1129/save local storage

e2e-tests/cypress/e2e/subjects_spec.js
Another test change to fix issues with the build
=> #1129 Change escape method

dashboard/src/components/access/InviteUsersToProject.vue
(cherry picked from commit e419dca9c6722e1601c680706ecdcb1d1cfccfe7)
=> #2473 Changed regex to match other validation regex

dashboard-prime/src/components/subjects/EditSubject.vue, dashboard-prime/src/components/utils/iconPicker/IconManager.vue, dashboard-prime/src/components/utils/inputForm/SkillsInputFormDialog.vue
=> T#2671/icon manager focus

dashboard/src/skills-display/components/skill/QuizFooter.vue, e2e-tests/cypress/e2e/inception/inception_spec.js, e2e-tests/cypress/e2e/quiz/client-display_quiz_spec.js, e2e-tests/cypress/e2e/quiz/client-display_run_quiz_spec.js, service/src/main/java/skills/skillLoading/SkillsLoader.groovy, service/src/main/java/skills/skillLoading/SubjectDataLoader.groovy, service/src/test/java/skills/intTests/clientDisplay/ClientDisplayGlobalBadgesSpec.groovy, service/src/test/java/skills/intTests/clientDisplay/SingleSkillSummarySpec.groovy
#3108: fixed so "Take Quiz" button is not showing for skills with prerequisites that are not yet achieved
=> #3109: fixed ability to run quizzes from skill under a badge
